
#ifndef __DOOM64EX_KEXLIB_FRAMEWORK_PIXMAP_H__
#define __DOOM64EX_KEXLIB_FRAMEWORK_PIXMAP_H__

#include "../kexlib.h"

KEX_C_BEGIN

KEXAPI int Pixmap_Return42();

KEX_C_END

#endif //__DOOM64EX_KEXLIB_FRAMEWORK_PIXMAP_H__
